using UnityEngine.UIElements;

public static class ToolkitLayoutContract
{
    public static bool Validate(VisualElement root)
    {
        return ToolkitTemplates.Require(root, "cancel-button", out Button _)
            && ToolkitTemplates.Require(root, "command-dock", out VisualElement _)
            && ToolkitTemplates.Require(root, "command-section", out VisualElement _)
            && ToolkitTemplates.Require(root, "currency-label", out Label _)
            && ToolkitTemplates.Require(root, "detail-actions", out VisualElement _)
            && ToolkitTemplates.Require(root, "detail-button", out Button _)
            && ToolkitTemplates.Require(root, "detail-close-button", out Button _)
            && ToolkitTemplates.Require(root, "detail-description", out Label _)
            && ToolkitTemplates.Require(root, "detail-equip-button", out Button _)
            && ToolkitTemplates.Require(root, "detail-icon", out VisualElement _)
            && ToolkitTemplates.Require(root, "detail-panel", out VisualElement _)
            && ToolkitTemplates.Require(root, "detail-scroll", out ScrollView _)
            && ToolkitTemplates.Require(root, "detail-targeting", out DropdownField _)
            && ToolkitTemplates.Require(root, "detail-title", out Label _)
            && ToolkitTemplates.Require(root, "encounter-actions", out VisualElement _)
            && ToolkitTemplates.Require(root, "field-toolbar", out VisualElement _)
            && ToolkitTemplates.Require(root, "focus-button", out Button _)
            && ToolkitTemplates.Require(root, "gameover-panel", out VisualElement _)
            && ToolkitTemplates.Require(root, "gameover-title", out Label _)
            && ToolkitTemplates.Require(root, "hud-root", out VisualElement _)
            && ToolkitTemplates.Require(root, "inventory-actions", out VisualElement _)
            && ToolkitTemplates.Require(root, "inventory-body", out ScrollView _)
            && ToolkitTemplates.Require(root, "inventory-button", out Button _)
            && ToolkitTemplates.Require(root, "inventory-close-button", out Button _)
            && ToolkitTemplates.Require(root, "inventory-detail", out Label _)
            && ToolkitTemplates.Require(root, "inventory-equip-button", out Button _)
            && ToolkitTemplates.Require(root, "inventory-list", out ScrollView _)
            && ToolkitTemplates.Require(root, "inventory-panel", out VisualElement _)
            && ToolkitTemplates.Require(root, "inventory-slot", out DropdownField _)
            && ToolkitTemplates.Require(root, "inventory-target", out DropdownField _)
            && ToolkitTemplates.Require(root, "main-content", out VisualElement _)
            && ToolkitTemplates.Require(root, "mana-bar", out ProgressBar _)
            && ToolkitTemplates.Require(root, "map-button", out Button _)
            && ToolkitTemplates.Require(root, "map-canvas", out VisualElement _)
            && ToolkitTemplates.Require(root, "map-close-button", out Button _)
            && ToolkitTemplates.Require(root, "map-connections", out VisualElement _)
            && ToolkitTemplates.Require(root, "map-description", out Label _)
            && ToolkitTemplates.Require(root, "map-dialog", out VisualElement _)
            && ToolkitTemplates.Require(root, "map-panel", out VisualElement _)
            && ToolkitTemplates.Require(root, "map-progress", out Label _)
            && ToolkitTemplates.Require(root, "map-recenter-button", out Button _)
            && ToolkitTemplates.Require(root, "map-scroll", out ScrollView _)
            && ToolkitTemplates.Require(root, "map-title", out Label _)
            && ToolkitTemplates.Require(root, "mark-entity-toggle", out Toggle _)
            && ToolkitTemplates.Require(root, "menu-button", out Button _)
            && ToolkitTemplates.Require(root, "menu-panel", out VisualElement _)
            && ToolkitTemplates.Require(root, "party-button", out Button _)
            && ToolkitTemplates.Require(root, "party-close-button", out Button _)
            && ToolkitTemplates.Require(root, "party-list", out ScrollView _)
            && ToolkitTemplates.Require(root, "party-panel", out VisualElement _)
            && ToolkitTemplates.Require(root, "pause-button", out Button _)
            && ToolkitTemplates.Require(root, "pause-panel", out VisualElement _)
            && ToolkitTemplates.Require(root, "pause-settings", out VisualElement _)
            && ToolkitTemplates.Require(root, "phase-label", out Label _)
            && ToolkitTemplates.Require(root, "restart-button", out Button _)
            && ToolkitTemplates.Require(root, "resume-button", out Button _)
            && ToolkitTemplates.Require(root, "speed-controls", out VisualElement _)
            && ToolkitTemplates.Require(root, "speed-fast-button", out Button _)
            && ToolkitTemplates.Require(root, "speed-normal-button", out Button _)
            && ToolkitTemplates.Require(root, "speed-slow-button", out Button _)
            && ToolkitTemplates.Require(root, "spell-list", out ScrollView _)
            && ToolkitTemplates.Require(root, "spell-section", out VisualElement _)
            && ToolkitTemplates.Require(root, "start-button", out Button _)
            && ToolkitTemplates.Require(root, "status-label", out Label _)
            && ToolkitTemplates.Require(root, "top-bar", out VisualElement _)
            && ToolkitTemplates.Require(root, "upgrade-list", out ScrollView _)
            && ToolkitTemplates.Require(root, "upgrade-panel", out VisualElement _)
            && ToolkitTemplates.Require(root, "upgrade-title", out Label _)
            && ToolkitTemplates.Require(root, "wave-button", out Button _)
            && ToolkitTemplates.Require(root, "wave-label", out Label _)
            && ToolkitTemplates.Require(root, "world-space", out VisualElement _);
    }
}
