using UnityEngine;

[CreateAssetMenu(menuName = "Custom/Data/Skills/IncreaseDamageOnDistanceProjectileBehaviour")]
public class IncreaseDamageOnDistanceProjectileBehaviourFactory : ProjectileBehaviourFactory<IncreaseDamageOnDistanceProjectileBehaviour, IncreaseDamageOnDistanceProjectileBehaviourData> {}